In [7]:
import pandas as pd
import numpy as np
import cpi
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed

# Load Data

In [2]:
artnet_2024 = pd.read_excel("D:\\MissTiny\\GitHub\\Creativity_Artnet\\Datasets\\ArtNet\\Artnet_Europe2024.xlsx")

In [3]:
artnet_2024 = artnet_2024.drop(columns=["Unnamed: 0"])

In [4]:
artnet_2024

,ID,lot id,artwork id,artist id,sale date,artist modifier,first,last,nationality,year born,...,currency,currency exchange rate,est lo usd,est hi usd,sale price usd,priceStatus,pricePhrase,has_image,sale year,artist
0,0,432409847,432409847,593645,2014-02-27 00:00:00,Circle Of,Rogier van der,Weyden,Flemish,1399,...,Euro,0.7293,13711.778418,13711.778418,54847.113671,Hammer,Sold,1,2014,Rogier van der Weyden
1,1,427653432,427653432,662454,2010-12-15 14:00:00,Workshop Of,Francesco di Gentile da,Fabriano,Italian,1370,...,Euro,0.7515,39920.159681,53226.879574,46200.931470,Premium,Sold,1,2010,Francesco di Gentile da Fabriano
2,2,430117545,430117545,643948,2012-10-27 00:00:00,NaN,Fra,Angelico,Italian,1400,...,Euro,0.7727,NaN,NaN,575902.678918,Hammer,Sold,1,2012,Fra Angelico
3,3,434483742,434483742,553790,2015-11-14 00:00:00,Follower Of,Hans,Memling,German,1430,...,Euro,0.9289,86123.371730,107654.214663,360426.310690,Premium,Sold,1,2015,Hans Memling
4,4,440596343,440596343,15130,2021-10-23 00:00:00,NaN,Martin,Schongauer,German,1445,...,Euro,0.8589,1397.135871,1397.135871,4889.975550,Hammer,Sold,1,2021,Martin Schongauer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358862,371772,444155415,444155415,576936,2024-11-25 18:00:00,NaN,H.R.,Giger,Swiss,1940,...,Swiss Franc,0.8874,4507.550146,6761.325220,9578.544061,Premium,Sold,1,2024,H.R. Giger
358863,371773,430447694,430447694,9440,2012-10-13 00:00:00,NaN,Raoul,De Keyser,Belgian,1930,...,British Pound,0.6223,24104.129841,32138.839788,30130.162301,Premium,Sold,1,2012,Raoul De Keyser
358864,371774,441326034,441326034,576936,2022-06-09 00:00:00,NaN,H.R.,Giger,Swiss,1940,...,US Dollar,1.0000,10000.000000,15000.000000,21250.000000,Premium,Sold,1,2022,H.R. Giger
358865,371775,434136558,434136558,7313,2015-06-11 00:00:00,NaN,Gotthard,Graubner,German,1930,...,Euro,0.8899,16855.826497,28093.044162,30902.348578,Premium,Sold,1,2015,Gotthard Graubner
358866,371776,440722158,440722158,634232,2021-12-08 00:00:00,NaN,Günther,Förg,German,1952,...,Euro,0.8829,4530.524408,6795.786612,6087.892174,Premium,Sold,1,2021,Günther Förg

In [4]:
def convert_price(i,row):
    price = cpi.inflate(row['sale price usd'], row['sale year'], to=2024)
    return i, price

In [5]:
number_size = 100000
range_start = 0
range_end = min(range_start+number_size,artnet_2024.shape[0])
N = min(number_size, artnet_2024.shape[0]-range_start)
print(f"{datetime.now():%Y-%m-%d %H:%M:%S}: Start")
prices = np.zeros(artnet_2024.shape[0], dtype=object)
while range_start < artnet_2024.shape[0]:
    print(f"{datetime.now():%Y-%m-%d %H:%M:%S}: Now at {range_start}")
    
    with ThreadPoolExecutor(max_workers=32) as ex:
        futures = {
            ex.submit(convert_price, i, artnet_2024.iloc[i]): i
            for i in range(range_start,range_end)
        }
        for fut in as_completed(futures):
            i, price = fut.result()
            prices[i] =price
            if i % 10000 == 0:
                print(f"{datetime.now():%Y-%m-%d %H:%M:%S}: {i}")

    range_start = range_start + N
    range_end = min(range_start+number_size,artnet_2024.shape[0])
    N = min(number_size, artnet_2024.shape[0]-range_start)
print(f"{datetime.now():%Y-%m-%d %H:%M:%S}: Ends")

2025-11-20 05:58:05: Start
2025-11-20 05:58:05: Now at 0
2025-11-20 05:58:19: 0
2025-11-20 06:07:51: 10000
2025-11-20 06:17:26: 20000
2025-11-20 06:26:35: 30000
2025-11-20 06:35:54: 40000
2025-11-20 06:44:34: 50000
2025-11-20 06:53:35: 60000
2025-11-20 07:02:46: 70000
2025-11-20 07:11:14: 80000
2025-11-20 07:19:42: 90000
2025-11-20 07:28:09: Now at 100000
2025-11-20 07:28:24: 100000
2025-11-20 07:37:05: 110000
2025-11-20 07:45:53: 120000
2025-11-20 07:54:46: 130000
2025-11-20 08:03:31: 140000
2025-11-20 08:11:51: 150000
2025-11-20 08:20:24: 160000
2025-11-20 08:29:09: 170000
2025-11-20 08:38:01: 180000
2025-11-20 08:46:45: 190000
2025-11-20 08:55:43: Now at 200000
2025-11-20 08:55:59: 200000
2025-11-20 09:04:51: 210000
2025-11-20 09:13:14: 220000
2025-11-20 09:21:35: 230000
2025-11-20 09:30:06: 240000
2025-11-20 09:38:32: 250000
2025-11-20 09:46:52: 260000
2025-11-20 09:55:43: 270000
2025-11-20 10:04:16: 280000
2025-11-20 10:13:02: 290000
2025-11-20 10:21:30: Now at 300000
2025-11-20 10:21:41: 300000
2025-11-20 10:31:05: 310000
2025-11-20 10:40:34: 320000
2025-11-20 10:49:49: 330000
2025-11-20 10:58:41: 340000
2025-11-20 11:07:38: 350000
2025-11-20 11:15:26: Ends

In [6]:
artnet_2024['price'] = prices

In [7]:
artnet_2024.to_excel("D:\\MissTiny\\GitHub\\Creativity_Artnet\\Datasets\\ArtNet\\Artnet_Europe2024_price.xlsx",index=False)

In [15]:
# number_size = artnet_2024.shape[0]
number_size = 100000
range_start = 0
range_end = min(range_start+number_size,artnet_2024.shape[0])
N = min(number_size, artnet_2024.shape[0]-range_start)

In [ ]:
print(f"{datetime.now():%Y-%m-%d %H:%M:%S}: Start")
prices = np.zeros(N, dtype=float)
with ThreadPoolExecutor(max_workers=32) as ex:
    futures = {
        ex.submit(convert_price, i, artnet_2024.iloc[i]): i
        for i in range(range_start,range_end)
    }
    completed = 0
    for fut in as_completed(futures):
        i, price = fut.result()
        prices[i-range_start]=price
        completed +=1
        if completed % 10000 == 0:
            print(f"{datetime.now():%Y-%m-%d %H:%M:%S}: {i}")
print(f"{datetime.now():%Y-%m-%d %H:%M:%S}: Ends")

2025-11-18 04:33:22: Start

In [ ]:
artnet_2024['price'] = prices

In [ ]:
artnet_2024.columns

# Merge same artwork with values

In [5]:
artnet_2024 = pd.read_excel("D:\\MissTiny\\GitHub\\Creativity_Artnet\\Datasets\\ArtNet\\Artnet_Europe2024_price.xlsx")

In [6]:
artnet_2024.columns

Index(['ID', 'lot id', 'artwork id', 'artist id', 'sale date',
       'artist modifier', 'first', 'last', 'nationality', 'year born',
       'year died', 'title', 'workyear modifier', 'workyear from',
       'workyear to', 'est lo', 'est hi', 'sale price', 'currency',
       'currency exchange rate', 'est lo usd', 'est hi usd', 'sale price usd',
       'priceStatus', 'pricePhrase', 'has_image', 'sale year', 'artist',
       'price'],
      dtype='object')

In [17]:
artnet_2024_merged = artnet_2024.groupby("artwork id").agg({
    "artwork id":"first",
    "artist id": "first",
    "first": "first",
    "last": "first",
    "nationality":'first',
    "year born":"first",
    "year died":"first",
    "title": "first",
    "workyear modifier":"first",
    "workyear from":"first",
    "workyear to":"first",
    "est lo usd":"mean",
    "est hi usd":"mean",
    "sale price usd":"mean",
    "artist":"first",
    "price":"mean"})

In [18]:
artnet_2024_merged.to_excel("D:\\MissTiny\\GitHub\\Creativity_Artnet\\Datasets\\ArtNet\\Artnet_Europe_2024_merged.xlsx",index=False)

# Check Data Points

In [14]:
artnet_2024_merge = pd.read_excel("D:\\MissTiny\\GitHub\\Creativity_Artnet\\Datasets\\ArtNet\\Artnet_Europe_2024_merged.xlsx")

In [15]:
artnet_2024_merge.shape

(355551, 16)

In [16]:
artnet_2024_merge.columns

Index(['artwork id', 'artist id', 'first', 'last', 'nationality', 'year born',
       'year died', 'title', 'workyear modifier', 'workyear from',
       'workyear to', 'est lo usd', 'est hi usd', 'sale price usd', 'artist',
       'price'],
      dtype='object')

In [18]:
value = artnet_2024_merge["price"].to_numpy()

In [19]:
np.save("D:\\MissTiny\\GitHub\\Creativity_Artnet\\Datasets\\value_2024.npy", value)

In [11]:
artnet_2024 = pd.read_excel("D:\\MissTiny\\GitHub\\Creativity_Artnet\\Datasets\\ArtNet\\Artnet_Europe2024_price.xlsx")

In [12]:
artnet_2024.shape

(358867, 29)

In [ ]:
artnet_2024['price']

In [13]:
artnet_2024[artnet_2024["artwork id"].duplicated()]["artwork id"].value_counts()

artwork id
6652     4
10714    4
746      4
17641    4
2369     4
        ..
6741     1
17326    1
15244    1
15661    1
7159     1
Name: count, Length: 2802, dtype: int64

# Remove Samples Sales at 2025

In [3]:
artnet_2024= pd.read_excel("D:\\MissTiny\\GitHub\\Creativity_Artnet\\Datasets\\ArtNet\\Artnet_Europe.xlsx")

In [19]:
artnet_2025.shape[0]

371778

In [17]:
artnet_2024 = artnet_2025[artnet_2025['sale year'] != 2025]

In [20]:
artnet_2024 = artnet_2024.reset_index()

In [22]:
artnet_2024= artnet_2024.drop(columns=["ID"])

In [24]:
artnet_2024.head()

,ID,lot id,artwork id,artist id,sale date,artist modifier,first,last,nationality,year born,...,currency,currency exchange rate,est lo usd,est hi usd,sale price usd,priceStatus,pricePhrase,has_image,sale year,artist
0,0,432409847,432409847,593645,2014-02-27 00:00:00,Circle Of,Rogier van der,Weyden,Flemish,1399,...,Euro,0.7293,13711.778418,13711.778418,54847.113671,Hammer,Sold,1,2014,Rogier van der Weyden
1,1,427653432,427653432,662454,2010-12-15 14:00:00,Workshop Of,Francesco di Gentile da,Fabriano,Italian,1370,...,Euro,0.7515,39920.159681,53226.879574,46200.931470,Premium,Sold,1,2010,Francesco di Gentile da Fabriano
2,2,430117545,430117545,643948,2012-10-27 00:00:00,NaN,Fra,Angelico,Italian,1400,...,Euro,0.7727,NaN,NaN,575902.678918,Hammer,Sold,1,2012,Fra Angelico
3,3,434483742,434483742,553790,2015-11-14 00:00:00,Follower Of,Hans,Memling,German,1430,...,Euro,0.9289,86123.371730,107654.214663,360426.310690,Premium,Sold,1,2015,Hans Memling
4,4,440596343,440596343,15130,2021-10-23 00:00:00,NaN,Martin,Schongauer,German,1445,...,Euro,0.8589,1397.135871,1397.135871,4889.975550,Hammer,Sold,1,2021,Martin Schongauer

In [1]:
artnet_2024.to_excel("D:\\MissTiny\\GitHub\\Creativity_Artnet\\Datasets\\ArtNet\\Artnet_Europe2024.xlsx",index=False)

NameError: name 'artnet_2024' is not defined